### ISSUE TITLE
import essentia

### ISSUE THREAD

**Issue by 0x10C** [oObqpdOo/MusicSimilarity-Python#1]
hi there:
           some essentia installation with python in macox stuck me , i follow the tutorial to install essentia but in the ./waf configuration step,Testing the pyext configuration always failed. i try lots of things but still not able to import in jupyter book. would you minding share your experience with me? thanks a lot

**Comment by oObqpdOo** [comment]
I was using Linux, so i am not sure about the OSX installation procedure. 
Have you tried the homebrew-essentia approach?
All Path variables are set accordingly?
Which python version do you use? 2.7 or 3.7?
